
SET MODE PostgreSQL;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user VARCHAR,
--  FOREIGN KEYS
);

CREATE TABLE IF NOT EXISTS genders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    gender VARCHAR,
--  FOREIGN KEYS
    userId INTEGER
);

CREATE TABLE IF NOT EXISTS sexes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    sex VARCHAR,
--  FOREIGN KEYS
    userId INTEGER
);